info.app:
  name: Hmpps Interventions Service
  version: 1.0

spring:
  main:
    banner-mode: off
  application:
    name: hmpps-interventions-service
  codec:
    max-in-memory-size: 10MB
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    mapper:
      default-view-inclusion: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        provider:
          hmppsauth:
            token-uri: ${hmppsauth.baseurl}/oauth/token
        registration:
          interventions-client:
            provider: hmppsauth
            authorization-grant-type: client_credentials
            scope: read,write
      resourceserver:
        jwt:
          issuer-uri: ${hmppsauth.baseurl}/issuer
          jwk-set-uri: ${hmppsauth.baseurl}/.well-known/jwks.json
  datasource:
    url: jdbc:postgresql://${postgres.uri}/${postgres.db}
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: PostgreSQLDialect
    show-sql: false
  batch:
    job:
      enabled: false  # don't run jobs at application startup
    jdbc:
      initialize-schema: never # we manage the spring batch schema with our own migrations
    concurrency:
      pool-size: 1 # run one job at a time...
      queue-size: 10000 # unless the number of queued jobs exceeds this number
    jobs:
      service-provider:
        performance-report:
          page-size: 100
          chunk-size: 20
      ndmis:
        performance-report:
          page-size: 100
          chunk-size: 20
  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

notify:
  enabled: true
  templates:
    referral-sent: "336f2158-d130-4c63-a59b-da12df15a5a3"
    referral-assigned: "f0fe2fce-df0f-46c0-839a-822037d39c28"
    action-plan-submitted: "83743b43-9abb-4ffb-913d-dc583ab22dbf"
    action-plan-approved: "f060e1ae-c2a6-4752-ad20-436120c5880b"
    appointment-not-attended: "21b14c86-30d2-4bf2-b355-8f3deb62ef69"
    concerning-behaviour: "a8ef6769-4c8e-4459-938c-19dd4b661b04"
    end-of-service-report-submitted: "f79cb53f-dc5c-42aa-947e-f599f9ad7942"
    initial-assessment-scheduled: "28256bed-6433-485c-857d-cb52a7937dff"
    service-provider-performance-report-ready: "9839e772-cd88-435d-9d18-61ea14d3531b"
    service-provider-performance-report-failed: "b4a09047-bf01-4ca1-ba55-f08bcce524f2"
    case-note-sent: "83868039-3d42-4af6-86da-df14e9d4a8b7"

interventions-ui:
  locations:
    service-provider:
      referral-details: "/service-provider/referrals/{id}/details"
      intervention-progress: "/service-provider/referrals/{id}/progress"
      action-plan: "/service-provider/referrals/{id}/action-plan"
      download-report: "/service-provider/performance-report/download?filename={filename}"
      case-note-details: "/service-provider/case-note/{id}"
    probation-practitioner:
      referral-details: "/probation-practitioner/referrals/{id}/details"
      intervention-progress: "/probation-practitioner/referrals/{id}/progress"
      supplier-assessment: "/probation-practitioner/referrals/{id}/supplier-assessment"
      action-plan: "/probation-practitioner/referrals/{id}/action-plan"
      session-feedback: "/probation-practitioner/referrals/{id}/appointment/{sessionNumber}/post-session-feedback"
      supplier-assessment-feedback: "/probation-practitioner/referrals/{id}/supplier-assessment/post-assessment-feedback"
      end-of-service-report: "/probation-practitioner/end-of-service-report/{id}"
      case-note-details: "/probation-practitioner/case-note/{id}"

community-api:
  locations:
    sent-referral: "/secure/offenders/crn/{crn}/referral/start/context/{contextName}"
    ended-referral: "/secure/offenders/crn/{crn}/referral/end/context/{contextName}"
    book-appointment: "/secure/offenders/crn/{crn}/sentence/{sentenceId}/appointments/context/{contextName}"
    reschedule-appointment: "/secure/offenders/crn/{crn}/appointments/{appointmentId}/reschedule/context/{contextName}"
    relocate-appointment: "/secure/offenders/crn/{crn}/appointments/{appointmentId}/relocate"
    appointment-outcome-request: "/secure/offenders/crn/{crn}/appointments/{appointmentId}/outcome/context/{contextName}"
    notification-request: "/secure/offenders/crn/{crn}/sentences/{sentenceId}/notifications/context/{contextName}"
    offender-access: "/secure/offenders/crn/{crn}/user/{username}/userAccess"
    managed-offenders: "/secure/staff/staffIdentifier/{staffIdentifier}/managedOffenders"
    staff-details: "/secure/staff/username/{username}"
    offender-managers: "/secure/offenders/crn/{crn}/allOffenderManagers"
  appointments:
    bookings:
      enabled: true
    office-location: CRSEXTL
    notes-field-qualifier: "{
      SERVICE_DELIVERY:'Service Delivery',
      SUPPLIER_ASSESSMENT:'Supplier Assessment'
      }"
    counts-towards-rar-days: "{
      SERVICE_DELIVERY:true,
      SUPPLIER_ASSESSMENT:false
      }"
  referrals:
      enabled: true
  integration-context: commissioned-rehabilitation-services

hmppsauth:
  api:
    locations:
      auth-user-groups: "/api/authuser/{username}/groups"
      auth-user-detail: "/api/authuser/{username}"
      user-email: "/api/user/{username}/email"
      user-detail: "/api/user/{username}"

assess-risks-and-needs:
  locations:
    create-supplementary-risk: "/risks/supplementary"

aws:
  s3:
    enabled: false
    provider: aws
    region: eu-west-2
  sns:
    enabled: true
    provider: aws
    region: eu-west-2

webclient:
  connect-timeout-seconds: 20
  read-timeout-seconds: 10
  write-timeout-seconds: 10
  hmpps-auth:
    max-retry-attempts: 2
    connect-timeout-seconds: 3
    read-timeout-seconds: 3
