replicaCount: 3

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  ports:
    app: 8080
    dataDictionary: 8080

ingress:
  hosts:
    - host: hmpps-interventions-service.apps.live-1.cloud-platform.service.justice.gov.uk
  migration:
    colour: blue

env_details:
  contains_live_data: true
  production_env: true

env:
  HMPPSAUTH_BASEURL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  INTERVENTIONSUI_BASEURL: "https://refer-monitor-intervention.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.probation.service.justice.gov.uk"
  COMMUNITYAPI_APPOINTMENTS_OUTCOME_ENABLED: "true"
  ASSESSRISKSANDNEEDS_BASEURL: "https://assess-risks-and-needs.hmpps.service.justice.gov.uk"
  SENTRY_ENVIRONMENT: "prod"
  AWS_S3_STORAGE_ENABLED: "true"
  AWS_S3_NDMIS_ENABLED: "true"
