apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: hmpps-interventions-service
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-suspect
  labels:
    app: hmpps-interventions-service
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "suspectApp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: performance-report
  labels:
    app: hmpps-interventions-service
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "performanceReportApp.selectorLabels" . | nindent 4 }}
