name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
      push:
        description: Push docker image to registry
        required: true
        default: false
        type: boolean
permissions:
  contents: read
  packages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  PACT_BROKER_BASE_URL: 'https://pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk'
  PACT_BROKER_USERNAME: 'interventions'
jobs:
  node_build:
    name: Node build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v2
    secrets: inherit
  node_unit_tests:
    name: Node unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@v2
    needs: [ node_build ]
    secrets: inherit
  node_integration_tests:
    name: Node integration tests
    runs-on: ubuntu-latest
    needs: [ node_build ]
    services:
      redis:
        image: redis:7.0
        ports:
          - 6380:6379
        env:
          ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd "redis-cli -p 6379 ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v5
      - name: Install latest npm
        run: sudo npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Get Wiremock
        shell: bash
        run: |
          curl -o wiremock.jar https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.9.1/wiremock-standalone-3.9.1.jar
      - name: Run integration tests
        shell: bash
        run: |
          nohup java -jar wiremock.jar --port 9091 &
          nohup npm run start:test &
          # Wait for Wiremock to be ready
          until curl -s http://localhost:9091/__admin; do
            echo "Waiting for Wiremock..."
            sleep 1
          done
          npm run int-test
      - name: Upload videos
        uses: actions/upload-artifact@v5
        with:
          name: integration-videos
          path: integration_tests/videos
      - name: Upload screenshots
        uses: actions/upload-artifact@v5
        with:
          name: integration-screenshots
          path: integration_tests/screenshots
  publish_pacts:
    name: Publish Pacts
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ node_integration_tests ]
    env:
      PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v5
      - name: Publish Pacts
        run: |
          PACT_BROKER_BASE_URL="${PACT_BROKER_BASE_URL}"
          PACT_BROKER_USERNAME="${PACT_BROKER_USERNAME}"
          PACT_BROKER_PASSWORD="${PACT_BROKER_PASSWORD}"
          if [ -d "pact/pacts" ]; then
            echo "Publishing Pacts for version $GITHUB_SHA..."
            npx --package=@pact-foundation/pact-cli@15.0.0 -c 'pact-broker publish pact/pacts/ \
              --consumer-app-version=$GITHUB_SHA \
              --broker-base-url=$PACT_BROKER_BASE_URL \
              --broker-username=$PACT_BROKER_USERNAME \
              --broker-password=$PACT_BROKER_PASSWORD'
          else
            echo "No pact/pacts directory found â€” skipping publish"
          fi
  helm_lint:
    strategy:
      matrix:
        environments: [ 'dev', 'preprod', 'prod' ]
    name: Helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  build:
    name: Build Docker image
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    needs:
      - node_integration_tests
      - node_unit_tests
      - publish_pacts
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push != '' && inputs.push || true }}
      docker_multiplatform: false
  deploy_dev:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_preprod:
    name: Deploy to Preprod
    needs:
      - build
      - helm_lint
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_prod:
    name: Deploy to Prod
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build.outputs.app_version }}'
  tag_pact_version:
    name: Tag Pact version
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
      - deploy_preprod
      - deploy_prod
    strategy:
      matrix:
        environment: [ dev, preprod, prod ]
    env:
      PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v5
      - name: Tag Pact version
        run: |
          sleep 10
          npx --package=@pact-foundation/pact-cli@15.0.0 -c 'pact-broker create-version-tag \
            --pacticipant="Interventions UI" \
            --version="${GITHUB_SHA}" \
            --tag="deployed:${{ matrix.environment }}" \
            --broker-base-url="$PACT_BROKER_BASE_URL" \
            --broker-username="$PACT_BROKER_USERNAME" \
            --broker-password="$PACT_BROKER_PASSWORD"'
