name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
      push:
        description: Push docker image to registry
        required: true
        default: false
        type: boolean
permissions:
  contents: read
  packages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  PACT_BROKER_BASE_URL: 'https://pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk'
  PACT_BROKER_USERNAME: 'interventions'
jobs:
  node_build:
    name: Node build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v2
    secrets: inherit
  node_unit_tests:
    name: Node unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@v2
    needs: [ node_build ]
    secrets: inherit
  generate_pacts:
    name: Generate Pacts and Publish
    uses: ./.github/workflows/generate_pacts_and_publish.yml
    needs: [ node_unit_tests ]
    secrets: inherit
  node_integration_tests:
    name: Node Integration Tests
    uses: ./.github/workflows/node_integration_tests.yml
    needs: [ node_build]
  helm_lint:
    strategy:
      matrix:
        environments: [ 'dev', 'preprod', 'prod' ]
    name: Helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  build:
    name: Build Docker image
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    needs:
      - node_integration_tests
      - node_unit_tests
      - generate_pacts
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push != '' && inputs.push || true }}
      docker_multiplatform: false
  deploy_dev:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_preprod:
    name: Deploy to Preprod
    needs:
      - build
      - helm_lint
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_prod:
    name: Deploy to Prod
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build.outputs.app_version }}'
  tag_pact_version:
    name: Tag Pact version
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
      - deploy_preprod
      - deploy_prod
    strategy:
      matrix:
        environment: [ dev, preprod, prod ]
    env:
      PACT_BROKER_PASSWORD: ${{ secrets.HMPPS_PACT_BROKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v5
      - name: Tag Pact version
        run: |
          sleep 10
          npx --package=@pact-foundation/pact-cli@15.0.0 -c 'pact-broker create-version-tag \
            --pacticipant="Interventions UI" \
            --version="${GITHUB_SHA}" \
            --tag="deployed:${{ matrix.environment }}" \
            --broker-base-url="$PACT_BROKER_BASE_URL" \
            --broker-username="$PACT_BROKER_USERNAME" \
            --broker-password="$PACT_BROKER_PASSWORD"'
