name: Security NPM Dependency Check
on:
  workflow_dispatch:
  schedule:
    - cron: "52 3 * * MON-FRI" # Every weekday at 03:52 UTC
jobs:
  security-npm-dependency-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@v2
    with:
      channel_id: ${{ vars.NONPROD_RELEASES_SLACK_CHANNEL || 'NO_SLACK' }}
    secrets: inherit
