name: Security Veracode Policy Scan
on:
  workflow_dispatch:
  schedule:
    - cron: "41 3 * * 1" # Every Monday at 03:41 UTC
jobs:
  security-veracode-policy-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
